e_reg/urls.py
from django.urls import path, re_path

from . import views

app_name = "e_reg"
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('select_property/', views.select_property, name='select_property'),
    path('my_profile/contact_update/', views.contact_update, name="contact_update"),
    path('my_profile/room_preference_update/', views.room_preference_update, name="room_preference_update"),
    path('my_profile/hotel_membersip_update/', views.hotel_membership_update, name="hotel_membership_update"),
    path('my_profile/', views.my_profile, name="my_profile"),
]

tidico_solutions/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('admin/', admin.site.urls),
    path('e_reg/', include('e_reg.urls', namespace="e_reg")),
]

e_reg/models.py
from django.conf import settings
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.urls import reverse
from django.utils import timezone
from multiselectfield import MultiSelectField

from .choices import COUNTRIES, ROOM_PREFERENCES, HOTEL_MEMBERSHIPS, PROPERTIES

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password=None):
        if not email:
            raise ValueError("Users must have an email address")

            user = self.model(email=self.normalize_email(email), username=username,)
            user.set_password(password)
            user.save()
            return user

    def create_superuser(self, email, username, first_name, last_name, password):
        user = self.create_user(email, username, first_name, last_name, password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    g_avatar = models.ImageField(blank=True, null=True, upload_to='avatars/')
    telephone_number = models.CharField(max_length=20, default="")
    address_street = models.CharField(max_length=255, default="")
    address_postcode = models.CharField(max_length=10, default="")
    address_city = models.CharField(max_length=30, default="")
    address_country = models.CharField(max_length=500, choices=COUNTRIES)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    room_preferences = MultiSelectField(max_length=500, choices=ROOM_PREFERENCES, blank=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "username"]

    def __str__(self):
        return "{}".format(self.first_name)

    def get_long_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('e_reg:my_profile')


class GuestUser(User):
    class Meta:
        ordering = ['-id',]

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('e_reg:my_profile')


class HotelMembership(models.Model):
    membership_programme_name = models.CharField(max_length=100, choices=HOTEL_MEMBERSHIPS, blank=True)
    membership_number = models.IntegerField(default="", blank=True, null=False)
    guestuser = models.ForeignKey(GuestUser, on_delete="CASCADE", related_name="membership")


    class Meta:
        ordering = ['-guestuser']
        verbose_name_plural = "Hotel Memberships"

    def __str__(self):
        return self.membership_programme_name


class HotelProperty(models.Model):
    name = models.CharField(max_length=255, choices=PROPERTIES, blank=True)
    membership = models.CharField(max_length=255, choices=HOTEL_MEMBERSHIPS, blank=True)
    room_features = models.CharField(max_length=255, default="", blank=True)

    class Meta:
        verbose_name_plural = "Hotel Properties"

    def __str__(self):
        return self.name

e_reg/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from multiselectfield import MultiSelectField

from . import models


class GuestUserCreateForm(UserCreationForm):
    class Meta:
        fields = ("first_name", "last_name", "email", "password1", "password2")
        model = models.GuestUser

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].label = "First Name"
        self.fields["last_name"].label = "Last Name"
        self.fields["email"].label = "Email address"


class GuestUserUpdateForm(forms.ModelForm):
    class Meta:
        model = models.GuestUser
        fields = [
            'first_name',
            'last_name',
            'email',
            'telephone_number',
            'address_street',
            'address_postcode',
            'address_city',
            'address_country',
        ]


class RoomPreferenceUpdateForm(forms.ModelForm):
    class Meta:
        model = models.GuestUser
        fields = [
            'room_preferences',
        ]


class HotelMembershipUpdateForm(forms.ModelForm):
    class Meta:
        model = models.HotelMembership
        fields = [
            'membership_programme_name',
            'membership_number',
        ]


HotelMembershipUpdateFormSet = forms.modelformset_factory(
    models.HotelMembership,
    form = HotelMembershipUpdateForm,
    extra=3,
    can_delete = True,
)

e_reg/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic

from itertools import chain

from . import forms
from e_reg.models import UserManager,User,GuestUser,HotelMembership,HotelProperty


class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("welcome")
    template_name = "e_reg/login.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogoutView(generic.RedirectView):
    url = reverse_lazy("welcome")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class SignUp(generic.CreateView):
    form_class = forms.GuestUserCreateForm
    success_url = reverse_lazy("e_reg:login")
    template_name = "e_reg/signup.html"


@login_required
def my_profile(request):
    guestuser = request.user
    hotelmembership = guestuser.guestuser.membership.all
    return render(request, "e_reg/my_profile.html", {"hotelmembership": hotelmembership})


@login_required
def select_property(request):
    hotelproperties = HotelProperty.objects.order_by("name")
    return render(request, "e_reg/select_property.html", {"hotelproperty": hotelproperties})


@login_required
def contact_update(request):
    guestuser = request.user
    form = forms.GuestUserUpdateForm(instance=guestuser)

    if request.method == "POST":
        form = forms.GuestUserUpdateForm(instance=guestuser, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "You have succesfully updated your Contact Card")
            return HttpResponseRedirect(guestuser.get_absolute_url())
    return render(request, "e_reg/contact_update.html", {'form': form})


@login_required
def room_preference_update(request):
    guestuser = request.user
    form = forms.RoomPreferenceUpdateForm(instance=guestuser)

    if request.method == "POST":
        form = forms.RoomPreferenceUpdateForm(instance=guestuser, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "You have succesfully updated your Room Preferences")
            return HttpResponseRedirect(guestuser.get_absolute_url())
    return render(request, "e_reg/room_preference_update.html", {'form': form})


@login_required
def hotel_membership_update(request):
    guestuser = request.user
    formset = forms.HotelMembershipUpdateFormSet(queryset=guestuser.guestuser.membership.all())

    if request.method == "POST":
        formset = forms.HotelMembershipUpdateFormSet(request.POST, queryset=guestuser.guestuser.membership.all())

        if formset.is_valid():
            memberships = formset.save(commit=False)
            for membership in formset.deleted_objects:
                membership.delete()

            for membership in memberships:
                membership.guestuser = guestuser.guestuser
                membership.save()
            messages.success(request, "You have succesfully updated your Hotel Memberships")
            return HttpResponseRedirect(guestuser.get_absolute_url())
    return render(request, "e_reg/hotel_membership_update.html", {'formset': formset})

e_reg/templates/e_reg/contact_update.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title %}Update Contact Card{% endblock %}

{% block content %}
<div class="container homebanner">
  <h1 class="title">Update Contact Card...</h1>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto px-4 py-3 col-md-11 bg-content my-2 text-white align-self-center rounded">
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <hr>
        <a href="{% url 'e_reg:my_profile' %}" class="btn">Back</a>
        <input type="submit" class="btn float-right" value="Update">
      </form>
    </div>
  </div>
</div>

{% endblock %}

e_reg/templates/e_reg/hotel_membership_update.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title %}Update Hotel Memberships{% endblock %}

{% block content %}
<div class="container homebanner">
  <h1 class="title">Update Hotel Memberships...</h1>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto px-4 py-3 col-md-11 bg-content my-2 text-white align-self-center rounded">
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_formset formset %}
        <hr>
        <a href="{% url 'e_reg:my_profile' %}" class="btn">Back</a>
        <input type="submit" class="btn float-right" value="Update">
      </form>
    </div>
  </div>
</div>

{% endblock %}

e_reg/templates/e_reg/login.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block title %}Login {% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">Login...</h1>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto px-4 py-3 col-md-5 mx-auto bg-content mt-2 mb-2 text-white align-self-center rounded">
      <h2>Log in to get full access to your own Hotel Profile</h2>
      <hr>
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn" type="submit">Login</button>
      </form>
    </div>

    <div class="mx-auto px-4 py-3 col-md-5 mx-auto bg-content mt-2 mb-2 text-white align-self-center rounded">
      <h3>Not yet a member?</h3>
      <hr>
      <p>Click <strong><a href="{% url 'e_reg:signup' %}">HERE</a></strong> to sign up instantly!</p>
    </div>
  </div>
</div>

{% endblock %}

e_reg/templates/e_reg/my_profile.html
{% extends "layout.html" %}

{% block title %}My Profile {% endblock %}

{% block content %}


<div class="container homebanner">
  <h1 class="title">{{ user.guestuser.first_name }}'s Profile</h1>
  <hr>
</div>

{% if messages %}
{% for message in messages %}
<div class="container col-md-4 alert alert-success alert-dismissible fade show align-self-center rounded" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}

<div class="container">
  <div class="accordion" id="accordionExample">
    <div class="bg-content text-white">

      <div class="" id="headingContact">
        <h5 class="mb-0">
          <button class="btn mx-auto col-sm-12 bg-content text-white" type="button" data-toggle="collapse" data-target="#collapseContact" aria-expanded="true" aria-controls="collapseContact">
            <div class="row">
              <div class="col-sm-12">
                <h2 class="pt-2">Contact Card</h2>
              </div>

            </div>
          </button>
        </h5>
      </div>
      <div id="collapseContact" class="collapse show" aria-labelledby="headingContact" data-parent="#accordionExample" style="">
        <div class="card-body">
          <div class="container">
            <div class="row">
              <div class="mx-auto mb-4 col-md-5">
                <table>
                  <th><u>Contact:</u></th>
                  <tr>
                    <td>Name:</td>
                    <td class="pl-4">{{ user.guestuser.last_name }}, {{ user.guestuser.first_name }}</td>
                  </tr>
                  <tr>
                    <td>Email:</td>
                    <td class="pl-4">{{ user.guestuser.email }}</td>
                  </tr>
                  <tr>
                    <td>Telephone:</td>
                    <td class="pl-4">{{ user.guestuser.telephone_number }}</td>
                  </tr>
                </table>
              </div>
              <div class="mx-auto col-md-5">
                <table>
                  <th><u>Address:</u></th>
                  <tr>
                    <td>Street:</td>
                    <td class="pl-4">{{ user.guestuser.address_street }}</td>
                  </tr>
                  <tr>
                    <td>Postcode:</td>
                    <td class="pl-4">{{ user.guestuser.address_postcode }}</td>
                  </tr>
                  <tr>
                    <td>City:</td>
                    <td class="pl-4">{{ user.guestuser.address_city }}</td>
                  </tr>
                  <tr>
                    <td>Country:</td>
                    <td class="pl-4">{{ user.guestuser.address_country }}</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="row justify-content-end">
              <div class="btn">
                <a href="/e_reg/my_profile/contact_update/"><u>edit</u></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="" id="headingRoom">
        <h5 class="mb-0">
          <button class="btn mx-auto col-sm-12 bg-content text-white collapsed" type="button" data-toggle="collapse" data-target="#collapseRoom" aria-expanded="false" aria-controls="collapseRoom">
            <div class="row">
              <div class="col-sm-12">
                <h2 class="pt-2">Room Preferences</h2>
              </div>
            </div>
          </button>
        </h5>
      </div>
      <div id="collapseRoom" class="collapse" aria-labelledby="headingRoom" data-parent="#accordionExample" style="">
        <div class="card-body">
          <div class="container">
            <div class="row">
              <div class="mx-auto px-4 col-md-11">
                <table>
                  {% if user.guestuser.room_preferences %}
                    {% for preference in user.guestuser.room_preferences %}
                    <tr>
                      <td class="py-1">{{ preference }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                      <td>Please add some room prefences! <br> Make sure the hotel knows exactly what you desire.</td>
                    </tr>
                  {% endif %}
                </table>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="row justify-content-end">
              <div class="btn">
                <a href="/e_reg/my_profile/room_preference_update/"><u>edit</u></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="" id="headingHabit">
        <h5 class="mb-0">
          <button class="btn mx-auto col-sm-12 bg-content text-white collapsed" type="button" data-toggle="collapse" data-target="#collapseHabit" aria-expanded="false" aria-controls="collapseHabit">
            <div class="row">
              <div class="col-sm-12">
                <h2 class="pt-2">Habits</h2>
              </div>
            </div>
          </button>
        </h5>
      </div>
      <div id="collapseHabit" class="collapse" aria-labelledby="headingHabit" data-parent="#accordionExample">
        <div class="card-body">
          ...
          <div class="container">
            <div class="row justify-content-end">
              <div class="btn">
                <a href="#"><u>edit</u></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="" id="headingExtra">
        <h5 class="mb-0">
          <button class="btn mx-auto col-sm-12 bg-content text-white collapsed" type="button" data-toggle="collapse" data-target="#collapseExtra" aria-expanded="false" aria-controls="collapseExtra">
            <div class="row">
              <div class="col-sm-12">
                <h2 class="pt-2">Extras</h2>
              </div>
            </div>
          </button>
        </h5>
      </div>
      <div id="collapseExtra" class="collapse" aria-labelledby="headingExtra" data-parent="#accordionExample">
        <div class="card-body">
          ...
          <div class="container">
            <div class="row justify-content-end">
              <div class="btn">
                <a href="#"><u>edit</u></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="" id="headingMember">
        <h5 class="mb-0">
          <button class="btn mx-auto col-sm-12 bg-content text-white collapsed" type="button" data-toggle="collapse" data-target="#collapseMember" aria-expanded="false" aria-controls="collapseMember">
            <div class="row">
              <div class="col-sm-12">
                <h2 class="pt-2">Hotel Memberships</h2>
              </div>
            </div>
          </button>
        </h5>
      </div>
      <div id="collapseMember" class="collapse" aria-labelledby="headingMember" data-parent="#accordionExample">
        <div class="card-body">
          <div class="container">
            <div class="row">
              <div class="mx-auto px-4 col-md-11">
                <table>
                  {% if hotelmembership %}
                    {% for hotelmemberships in hotelmembership %}
                    <tr>
                      <td class="py-1">{{ hotelmemberships.membership_programme_name }}</td>
                      <td class="pl-4">{{ hotelmemberships.membership_number }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                      <td>Already a member with any Hotel Chains? <br> Store them here to have easy access to them.</td>
                    </tr>
                  {% endif %}
                </table>
              </div>
            </div>
          </div>
          <div class="container">
            <div class="row justify-content-end">
              <div class="btn">
                <a href="{% url 'e_reg:hotel_membership_update' %}"><u>edit</u></a>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}

e_reg/templates/e_reg/room_preference_update.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title %}Update Room Preferences{% endblock %}

{% block content %}
<div class="container homebanner">
  <h1 class="title">Update Room Preferences...</h1>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto px-4 py-3 col-md-11 bg-content my-2 text-white align-self-center rounded">
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <hr>
        <a href="{% url 'e_reg:my_profile' %}" class="btn">Back</a>
        <input type="submit" class="btn float-right" value="Update">
      </form>
    </div>
  </div>
</div>

{% endblock %}

e_reg/templates/e_reg/select_property.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block title %}Select Property {% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">Select Property</h1>
  <hr>
</div>

<div class="container">
  <select class="form-control">
    <option>Select Property</option>
    <option disabled>---------------</option>
    {% for property in hotelproperty %}
    <option>{{ property.name }}</option>
    {% endfor %}
  </select>
  <ul>
    <li>search bar</li>
    <li>dropdown list</li>
    <ol>
      <li>property specs</li>
    </ol>
  </ul>
</div>

{% endblock %}

e_reg/templates/e_reg/signup.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title %}Sign Up!{% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">Sign up now...</h1>
  <hr>
</div>

<div class="container mb-3">
  <div class="row">
    <div class="col-md order-md-2 px-4 py-3 col-md-8 mx-auto bg-content mt-2 text-white align-self-center rounded">
      <h3 class="my-2">Sign Up Now</h3>
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <hr>
        <input type="submit" class="float-right btn" value="Sign Up">
      </form>
    </div>
  </div>
</div>

{% endblock %}