e_reg/urls.py
from django.urls import path, re_path

from . import views

app_name = "e_reg"
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('select_property/', views.select_property, name='select_property'),
    path('my_profile/contact_update/', views.contact_update, name="contact_update"),
    path('my_profile/room_preference_update/', views.room_preference_update, name="room_preference_update"),
    path('my_profile/hotel_membersip_update/', views.hotel_membership_update, name="hotel_membership_update"),
    path('my_profile/', views.my_profile, name="my_profile"),
]

tidico_solutions/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('admin/', admin.site.urls),
    path('e_reg/', include('e_reg.urls', namespace="e_reg")),
]

templates/about.html
{% extends 'layout.html' %}

{% block title %}About {% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">About TIDICO Solutions...</h1>
  <hr>
</div>

<div class="container mb-2">
  <div class="row">
    <div class="col-md order-md-2 px-4 py-3 bg-content mt-2 text-white align-self-center rounded">
      <p>
        <strong><em>TIDICO Solutions</em></strong> believes in the benefits and advantages technology has to offer the hospitality industry to increase guest satisfaction
        while making processes more efficient.
      </p>
      <p>
        Having spent many years working in various Front Office positions, the importance of building personal connections with guests is the pinnacle of providing an
        enjoyable and memorable stay.
        At TIDICO Solutions, we aim to provide the same rapport with guests by reaching out to guests on a personal level through a platform where their information is
        stored and shared prior to guest arrival,
        and where guests are able to place special requests and orders prior to arrival so the property they will visit may be prepared in advance.
      </p>
      <p>
        The E-Reg platform allows guests to fill in all the fields required at every hotel one visits.
      </p>
    </div>
  </div>
</div>

{% endblock %}

templates/contact.html
{% extends 'layout.html' %}

{% block title %}Contact {% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">Contact...</h1>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto px-4 py-3 col-md-5 mx-auto bg-content mt-2 text-white align-self-center rounded">
      <ul>
        <li class="mb-2">Telephone: +31 (0) 629 400 311</li>
        <li class="mb-2">Email: info@tidico-solutions.com</li>
        <ul class="mb-2">Address:
          <li class="mx-4">Bermuda 104</li>
          <li class="mx-4">1505XC, Zaandam</li>
        </ul>
        <li class="mb-2">KVK Nummer: </li>
    </div>
  </div>
</div>

{% endblock %}

templates/forgot_password.html
{% extends 'layout.html' %}

{% block title %}Forgot Your Password? {% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">Forgot Your Password?...</h1>
  <hr>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT" rel="stylesheet">
    <title>{% block title %}{% endblock %} | TIDICO Solutions</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-gradient fixed-top">
        <a class="navbar-brand" href="{% url 'welcome' %}"><img src="{% static 'Images/logo.svg' %}" height=40 alt="Company Logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav navbar-nav">
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'welcome' %}">Home</a></li>
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'about' %}">About</a></li>
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li role="separator" class="divider"></li>
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'e_reg:my_profile' %}">Profile</a></li>
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'e_reg:select_property' %}">Select Property</a></li>
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'e_reg:logout' %}">Log out</a></li>
            {% else %}
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'e_reg:login' %}">Login</a></li>
            <li class="nav-item text-center"><a class="nav-link" href="{% url 'forgot_password' %}">Forgot Password?</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock %}

    <footer class="main-footer mt-auto pt-3"><small>
      <div class="container-fluid">
        <a class="mx-2" href="{% url 'welcome' %}">Home</a>
        <a class="mx-2" href="{% url 'about' %}">About</a>
        <a class="mx-2" href="{% url 'contact' %}">Contact</a>
        <hr>
        <p>Disclaimer: Please be informed that all preferences filled out with TIDICO Solutions are honoured based on the Hotel's availability and are not confirmed until arrival at the property.</p>
        <div class="row">
          <p class="col">Copyright (c) 2017 Copyright Holder All Rights Reserved.</p>
          <p class="col text-right">Powered by: <img src="{% static 'Images/Logo.JPG' %}" width=75 height=25 alt="TIDICO Solutions"></p>
        </div>
      </div>
    </small></footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/welcome.html
{% extends 'layout.html' %}

{% block title %}Welcome!{% endblock %}

{% block content %}

<div class="container homebanner">
  <h1 class="title">Welcome {{ user.guestuser.first_name }}...</h1>
  <hr>
</div>

<div class="container mb-2">
  {% if user.is_authenticated %}
  <div class="row">
    <div class="col-md order-md-2 px-4 py-3 col-md-4 mx-auto bg-content mt-2 text-white align-self-center rounded">
      <h2 class="my-2">Quick Access</h2>
      <hr>
      <a class="nav-item nav-link btn mr-2 my-2 btn-secondary" href="{% url 'e_reg:my_profile' %}"><strong>Profile</strong></a>
      <a class="nav-item nav-link btn mr-2 my-2 btn-secondary" href="{% url 'e_reg:select_property' %}"><strong>Select Property</strong></a>
      <a class="nav-item nav-link btn mr-2 my-2 btn-secondary" href="#"><strong>Stay History</strong></a>
    </div>

    <div class="col-md order-md-1 px-4 py-3 col-md-6 mx-auto bg-content mt-2 text-white align-self-center rounded">
  {% else %}
  <div class="row">
    <div class="col-md order-md-2 px-4 py-3 col-md-6 mx-auto bg-content mt-2 text-white align-self-center rounded">
      <h2 class="my-2">Enter as <i><strong>Guest</strong></i> or <i><strong>Sign Up Now</strong></i></h2>
      <hr>
      <form action="" method="post">
        <h3 class="my-2">Enter as guest</h3>
        <label for="guest_email">Email:</label><br>
        <input type="email" class="form-control" id="guest_email" name="guest_email" placeholder="example@email.com" required><br>
        <label for="guest_password">Invitation Code:</label><br>
        <input type="password" class="form-control" id="guest_password" name="guest_password" placeholder="Invitation Code" required><br>
        <button class="btn" type="submit">Continue</button>
      </form>
      <hr>
      <form action="" method="post">
        <h3 class="my-2">Sign Up Now</h3>
        <br>
        <p>Click <strong><a href="{% url 'e_reg:signup' %}">HERE</a></strong> to sign up instantly!</p>
      </form>
      <!-- <ul>
        <li>Enter as guest using provided hotel code for one time use</li>
        <li>Become a member now to store details for future stays at partner hotels</li>
        <li>Limited profile options as one-time guest, full profile and preference access as member</li>
        <li>Limited: Only registration card access </br>Room prep details, i.e. Anti allegic bedding </br> Room service orders.</li>
        <li>Full profile: All Limited options </br> Room types, i.e. HI, View, FE </br> Food preferences + allergies </br> Membership benefits.</li>
      </ul> -->
    </div>

    <div class="col-md order-md-1 px-4 py-3 col-md-4 mx-auto bg-content mt-2 text-white align-self-center rounded">
    {% endif %}

      <h2 class="my-2"><strong>Membership</strong></h2>
      <hr>
      <h3>This is how it works...</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <!--
      <ul>
        <li><strong>TIDICOmforts</strong></li>
        <li>Move up status tiers</li>
        <ul>
          <li>Alpha</li>
          <li>Beta</li>
          <li>Omega</li>
        </ul>
        <li>Earn and Spend style:</li>
        <ul>
          <li>Earn points according to tier level</li>
          <li>Use points to buy benefits</li>
          <li>Option to buy points directly</li>
        </ul>
      </ul> -->
    </div>
  </div>
</div>

{% endblock %}